### ISSUE TITLE
Extend session duration

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#194]
Now that we stay logged in to different tabs, we still need to extend the session duration. I propose one week.

**Comment by Powersource** [comment]
For reference we have all of these options

![image](https://user-images.githubusercontent.com/1427063/104460490-7923ec80-55ae-11eb-83f5-f312cd47de15.png)

I'm gonna try upping "SSO Session Max" to 24*7 hours. Note that this probably won't persist between browser restarts because we haven't enabled the "Remember me" checkbox (which is just for remembering through browser restarts apparently), haven't enabled that one yet because we anyway had troubles getting the session when e.g. opening a new tab, but that might be more possible now that we did https://github.com/Edgeryders-Participio/realities/pull/192

**Comment by Powersource** [comment]
Actually I'm gonna change it to this

![image](https://user-images.githubusercontent.com/1427063/104461482-ade47380-55af-11eb-8661-d91989c99d12.png)

as well as enable the Remember me checkbox (which then uses the latter timeouts)

**Comment by Powersource** [comment]
Niice, now your session persists after a (brief) browser restart. I wonder what happens if you keep your browser closed for a few hours/overnight. Maybe we'll need to increase SSO Session Idle Remember Me to something like 24 hours.

**Comment by Powersource** [comment]
Updated SSO session idle remember me to 24 hours now, hopefully that's what would make it persist overnight.

**Comment by Powersource** [comment]
Yess seems to work for me. Reopen this issue/a new one if you want it extended further/you run into new bugs
